[default]
SQLALCHEMY_DATABASE_URI = "postgresql://postgres:1python1@localhost/mimoso"
TITLE = "Api"
EXTENSIONS = [
    "vite.extension.database:init_app",
    "vite.extension.command:init_app",
    "vite.blueprint.webui:init_app",
    "vite.blueprint.restapi:init_app"
]

[production]
