[default]


SQLALCHEMY_DATABASE_URI = " sqlite:////tmp/test.db"


TITLE = "Api mimoso"
EXTENSIONS = [
    "vite.extension.database:init_app",
    "vite.extension.docs:init_app",
    "vite.extension.command:init_app",
    "vite.blueprint.webui:init_app",
    "vite.blueprint.restapi:init_app"
]





